In [1]:
import numpy as np

In [2]:
a=np.array([[1,2,3],
           [4,5,6]])

In [3]:
a.sum(axis=1)

array([ 6, 15])

In [4]:
a.sum(axis=0)

array([5, 7, 9])

In [5]:
b=np.array([[17,8,9],
           [12,18,0]])

In [6]:
np.dot(a,b.transpose())

array([[ 60,  48],
       [162, 138]])

In [7]:
np.cross(a,b)

array([[  -6,   42,  -26],
       [-108,   72,   12]])

In [8]:
%%time
np.sort(b, axis=0,kind='mergeshort')

CPU times: total: 0 ns
Wall time: 0 ns


array([[12,  8,  0],
       [17, 18,  9]])

In [9]:
z=np.array([23,4,5,77,24,77,13,66,88,99,100,1,2,8,17,20,101,105,106,102,103,104,109,110,112,113,116,115,117,119,120,121,131,141])

In [10]:
%time
np.sort(z,axis=0,kind='quicksort')

CPU times: total: 0 ns
Wall time: 0 ns


array([  1,   2,   4,   5,   8,  13,  17,  20,  23,  24,  66,  77,  77,
        88,  99, 100, 101, 102, 103, 104, 105, 106, 109, 110, 112, 113,
       115, 116, 117, 119, 120, 121, 131, 141])

In [11]:
fol=np.array([1,2,3,4,5,6,7,98,0,12,23,14,25,15,17,16,19,18,20,22,21,30,34,35,38,40,44,45,46,47,48,49,50])

In [12]:
%time
np.sort(fol, axis=-1, kind='heapsort')

CPU times: total: 0 ns
Wall time: 0 ns


array([ 0,  1,  2,  3,  4,  5,  6,  7, 12, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 25, 30, 34, 35, 38, 40, 44, 45, 46, 47, 48, 49, 50, 98])

In [16]:
gol=np.array([1,2,3,4,5,6,7,98,0,12,23,14,25,15,17,16,19,18,20,22,21,30,34,35,38,40,44,45,46,47,48,49,50,56,57,58,99,10,58,88,87,80])

In [20]:
%time
np.sort(gol, axis=-1,kind='stable')

CPU times: total: 0 ns
Wall time: 0 ns


array([ 0,  1,  2,  3,  4,  5,  6,  7, 10, 12, 14, 15, 16, 17, 18, 19, 20,
       21, 22, 23, 25, 30, 34, 35, 38, 40, 44, 45, 46, 47, 48, 49, 50, 56,
       57, 58, 58, 80, 87, 88, 98, 99])